/**
 * AUTOMATICALLY GENERATED FILE - DO NOT EDIT DIRECTLY
 * 
 * This file was generated by scripts/generate-command-types.ts
 * To update, run: bun run generate-types
 * 
 * Type definitions for CLI commands based on directory structure in src/commands/
 * - Root commands (module) become "module" (e.g., "spotify")
 * - First-level subcommands become "module:subcommand" (e.g., "spotify:playlists")
 * - Nested subcommands become "module:subcommand:subsubcommand" (e.g., "spotify:playlists:test")
 */

/**
 * Base command modules (top-level directories in src/commands/)
 */
export type CommandModule = 
  | "spotify";

/**
 * spotify direct subcommands (first-level subdirectories in src/commands/spotify/)
 */
export type SpotifySubcommand = 
  | "song"
  | "playlists";

/**
 * All available commands based on directory structure
 */
export type Commands = 
  | CommandModule
  | `spotify:${SpotifySubcommand}`;
